PLUGIN_NAME=		deepinspector
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Deep Packet Inspector with Zero Trust and Industrial OT support
PLUGIN_MAINTAINER=	pierpaolo.casati@student.supsi.ch
PLUGIN_TIER=		3
PLUGIN_WWW=		https://git.consoli.ch/students/20250400_lavsem/moretto/
PLUGIN_DIR=		service
PLUGIN_DEPENDS= os-validationcore

.include "../../Mk/plugins.mk"