<?php

/*
 * Copyright (C) 2024 Advanced Network Inspector
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

namespace OPNsense\AdvInspector\Api;

use OPNsense\Base\ApiControllerBase;

/**
 * Class AlertsController
 * 
 * Provides API endpoints for managing and retrieving security alerts
 * generated by the Advanced Network Inspector. Handles real-time alert
 * monitoring, filtering, and historical data retrieval.
 *
 * @package OPNsense\AdvInspector\Api
 * @author Pierpaolo Casati
 */
class AlertsController extends ApiControllerBase
{
    /**
     * Path to the main alerts log file
     */
    private const LOG_FILE = '/var/log/advinspector_alerts.log';
    
    /**
     * Maximum number of alerts to return in a single request
     */
    private const MAX_ALERTS_LIMIT = 500;
    
    /**
     * Default number of alerts to return
     */
    private const DEFAULT_ALERTS_LIMIT = 100;

    /**
     * Retrieve a list of security alerts with filtering and pagination support
     * 
     * Supports query parameters:
     * - limit: Maximum number of alerts to return (default: 100, max: 500)
     * - since: ISO timestamp to filter alerts newer than specified time
     * - severity: Filter by alert severity level (low, medium, high, critical)
     * - src_ip: Filter by source IP address
     * - dst_ip: Filter by destination IP address
     * - protocol: Filter by protocol (tcp, udp, icmp, etc.)
     * 
     * @return array JSON response containing alerts data or error information
     */
    public function listAction()
    {
        $logFile = self::LOG_FILE;
        
        // Check if log file exists
        if (!file_exists($logFile)) {
            return [
                'status' => 'ok', 
                'data' => [],
                'total' => 0,
                'message' => 'No alerts log file found'
            ];
        }

        // Check if log file is readable
        if (!is_readable($logFile)) {
            return [
                'status' => 'error', 
                'message' => 'Alerts log file is not readable - check file permissions'
            ];
        }

        try {
            // Get query parameters with defaults
            $limit = min(
                (int)($this->request->get('limit') ?: self::DEFAULT_ALERTS_LIMIT), 
                self::MAX_ALERTS_LIMIT
            );
            $since = $this->request->get('since');
            $severity = $this->request->get('severity');
            $srcIp = $this->request->get('src_ip');
            $dstIp = $this->request->get('dst_ip');
            $protocol = $this->request->get('protocol');

            // Read log file with error handling
            $lines = @file($logFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
            if ($lines === false) {
                throw new \RuntimeException("Unable to read alerts log file");
            }

            $alerts = [];
            $totalProcessed = 0;
            
            // Process log entries in reverse order (newest first)
            foreach (array_reverse($lines) as $line) {
                $totalProcessed++;
                
                // Parse JSON log entry
                $entry = json_decode($line, true);
                if (!is_array($entry)) {
                    continue; // Skip malformed entries
                }

                // Apply filters
                if (!$this->matchesFilters($entry, $since, $severity, $srcIp, $dstIp, $protocol)) {
                    continue;
                }

                // Enhance entry with additional metadata
                $entry = $this->enhanceAlertEntry($entry);
                $alerts[] = $entry;

                // Stop if we've reached the limit
                if (count($alerts) >= $limit) {
                    break;
                }
            }

            return [
                'status' => 'ok',
                'data' => $alerts,
                'total' => count($alerts),
                'processed' => $totalProcessed,
                'filters_applied' => $this->getAppliedFilters($since, $severity, $srcIp, $dstIp, $protocol)
            ];

        } catch (\Exception $e) {
            return [
                'status' => 'error',
                'message' => 'Failed to retrieve alerts: ' . $e->getMessage()
            ];
        }
    }

    /**
     * Get alert statistics and summary information
     * 
     * Provides aggregated statistics about alerts including:
     * - Total alert count by time period
     * - Alert distribution by severity
     * - Top source/destination IPs
     * - Protocol distribution
     * - Recent alert trends
     * 
     * @return array JSON response with statistical data
     */
    public function statsAction()
    {
        $logFile = self::LOG_FILE;
        
        if (!file_exists($logFile) || !is_readable($logFile)) {
            return [
                'status' => 'error',
                'message' => 'Alerts log file not accessible'
            ];
        }

        try {
            $lines = @file($logFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
            if ($lines === false) {
                throw new \RuntimeException("Unable to read alerts log file");
            }

            $stats = [
                'total_alerts' => 0,
                'severity_distribution' => [],
                'protocol_distribution' => [],
                'top_sources' => [],
                'top_destinations' => [],
                'hourly_trend' => [],
                'last_updated' => null
            ];

            $sourceIps = [];
            $destinationIps = [];
            $protocols = [];
            $severities = [];
            $hourlyBuckets = [];

            foreach ($lines as $line) {
                $entry = json_decode($line, true);
                if (!is_array($entry)) {
                    continue;
                }

                $stats['total_alerts']++;

                // Track source IPs
                if (isset($entry['src'])) {
                    $sourceIps[$entry['src']] = ($sourceIps[$entry['src']] ?? 0) + 1;
                }

                // Track destination IPs
                if (isset($entry['dst'])) {
                    $destinationIps[$entry['dst']] = ($destinationIps[$entry['dst']] ?? 0) + 1;
                }

                // Track protocols
                if (isset($entry['protocol'])) {
                    $protocols[$entry['protocol']] = ($protocols[$entry['protocol']] ?? 0) + 1;
                }

                // Track severity (infer from reason or set default)
                $severity = $this->inferSeverity($entry);
                $severities[$severity] = ($severities[$severity] ?? 0) + 1;

                // Track hourly distribution
                if (isset($entry['timestamp'])) {
                    $hour = date('Y-m-d H', strtotime($entry['timestamp']));
                    $hourlyBuckets[$hour] = ($hourlyBuckets[$hour] ?? 0) + 1;
                    $stats['last_updated'] = max($stats['last_updated'] ?: '', $entry['timestamp']);
                }
            }

            // Sort and limit top entries
            arsort($sourceIps);
            arsort($destinationIps);
            arsort($protocols);
            ksort($hourlyBuckets);

            $stats['severity_distribution'] = $severities;
            $stats['protocol_distribution'] = $protocols;
            $stats['top_sources'] = array_slice($sourceIps, 0, 10, true);
            $stats['top_destinations'] = array_slice($destinationIps, 0, 10, true);
            $stats['hourly_trend'] = array_slice($hourlyBuckets, -24, 24, true); // Last 24 hours

            return [
                'status' => 'ok',
                'data' => $stats
            ];

        } catch (\Exception $e) {
            return [
                'status' => 'error',
                'message' => 'Failed to generate alert statistics: ' . $e->getMessage()
            ];
        }
    }

    /**
     * Clear all alerts from the log file
     * 
     * WARNING: This action is irreversible and will permanently delete
     * all alert history. Use with caution in production environments.
     * 
     * @return array JSON response indicating success or failure
     */
    public function clearAction()
    {
        if (!$this->request->isPost()) {
            return [
                'status' => 'error',
                'message' => 'Only POST method allowed for clear operation'
            ];
        }

        $logFile = self::LOG_FILE;

        try {
            if (file_exists($logFile)) {
                if (!is_writable($logFile)) {
                    return [
                        'status' => 'error',
                        'message' => 'Alerts log file is not writable'
                    ];
                }

                // Truncate the file
                if (file_put_contents($logFile, '') === false) {
                    throw new \RuntimeException("Failed to clear alerts log file");
                }
            }

            return [
                'status' => 'ok',
                'message' => 'Alerts log cleared successfully'
            ];

        } catch (\Exception $e) {
            return [
                'status' => 'error',
                'message' => 'Failed to clear alerts: ' . $e->getMessage()
            ];
        }
    }

    /**
     * Check if an alert entry matches the specified filters
     * 
     * @param array $entry The alert entry to check
     * @param string|null $since ISO timestamp filter
     * @param string|null $severity Severity level filter
     * @param string|null $srcIp Source IP filter
     * @param string|null $dstIp Destination IP filter
     * @param string|null $protocol Protocol filter
     * @return bool True if entry matches all filters
     */
    private function matchesFilters($entry, $since, $severity, $srcIp, $dstIp, $protocol)
    {
        // Filter by timestamp
        if ($since && isset($entry['timestamp'])) {
            if (strcmp($entry['timestamp'], $since) <= 0) {
                return false;
            }
        }

        // Filter by severity
        if ($severity) {
            $entrySeverity = $this->inferSeverity($entry);
            if (strcasecmp($entrySeverity, $severity) !== 0) {
                return false;
            }
        }

        // Filter by source IP
        if ($srcIp && isset($entry['src'])) {
            if (stripos($entry['src'], $srcIp) === false) {
                return false;
            }
        }

        // Filter by destination IP
        if ($dstIp && isset($entry['dst'])) {
            if (stripos($entry['dst'], $dstIp) === false) {
                return false;
            }
        }

        // Filter by protocol
        if ($protocol && isset($entry['protocol'])) {
            if (strcasecmp($entry['protocol'], $protocol) !== 0) {
                return false;
            }
        }

        return true;
    }

    /**
     * Enhance alert entry with additional computed fields
     * 
     * @param array $entry Original alert entry
     * @return array Enhanced alert entry
     */
    private function enhanceAlertEntry($entry)
    {
        // Add computed severity
        $entry['severity'] = $this->inferSeverity($entry);

        // Add human-readable timestamp
        if (isset($entry['timestamp'])) {
            $entry['formatted_timestamp'] = date('Y-m-d H:i:s', strtotime($entry['timestamp']));
        }

        // Add connection summary
        if (isset($entry['src'], $entry['dst'], $entry['port'])) {
            $entry['connection'] = "{$entry['src']} → {$entry['dst']}:{$entry['port']}";
        }

        // Add alert age
        if (isset($entry['timestamp'])) {
            $entry['age_seconds'] = time() - strtotime($entry['timestamp']);
        }

        return $entry;
    }

    /**
     * Infer severity level from alert entry content
     * 
     * @param array $entry Alert entry
     * @return string Severity level (low, medium, high, critical)
     */
    private function inferSeverity($entry)
    {
        $reason = strtolower($entry['reason'] ?? '');
        
        // Critical severity indicators
        if (strpos($reason, 'block') !== false || 
            strpos($reason, 'attack') !== false || 
            strpos($reason, 'intrusion') !== false) {
            return 'critical';
        }
        
        // High severity indicators
        if (strpos($reason, 'suspicious') !== false || 
            strpos($reason, 'malware') !== false || 
            strpos($reason, 'exploit') !== false) {
            return 'high';
        }
        
        // Medium severity indicators
        if (strpos($reason, 'alert') !== false || 
            strpos($reason, 'warning') !== false) {
            return 'medium';
        }
        
        // Default to low severity
        return 'low';
    }

    /**
     * Get summary of applied filters for response metadata
     * 
     * @param string|null $since Timestamp filter
     * @param string|null $severity Severity filter
     * @param string|null $srcIp Source IP filter
     * @param string|null $dstIp Destination IP filter
     * @param string|null $protocol Protocol filter
     * @return array Applied filters summary
     */
    private function getAppliedFilters($since, $severity, $srcIp, $dstIp, $protocol)
    {
        $filters = [];
        
        if ($since) $filters['since'] = $since;
        if ($severity) $filters['severity'] = $severity;
        if ($srcIp) $filters['src_ip'] = $srcIp;
        if ($dstIp) $filters['dst_ip'] = $dstIp;
        if ($protocol) $filters['protocol'] = $protocol;
        
        return $filters;
    }
}