apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-ds
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeout: 30

  - name: OPNsense API (JSON)
    type: marcusolsson-json-datasource
    uid: json-ds
    access: proxy
    url: http://192.168.216.50:3000/api/v1
    jsonData:
      timeout: 30
      tlsSkipVerify: true
    editable: true