<?php
/*
 * Copyright (C) 2024 Advanced Network Inspector
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

namespace OPNsense\AdvInspector;

/**
 * Class LogsController
 *
 * Web interface controller for the Advanced Network Inspector log management and analysis system.
 * This controller provides the main entry point for comprehensive log viewing, analysis, and
 * forensic investigation capabilities through a web-based interface.
 *
 * The LogsController serves as the presentation layer for log management functionality,
 * rendering the main interface that allows administrators and security analysts to access,
 * filter, search, and analyze both packet logs and security alerts generated by the
 * Advanced Network Inspector system.
 *
 * Key Interface Features:
 * - Unified log viewer with multiple log type support (alerts, packets, system events)
 * - Advanced filtering and search capabilities with real-time updates
 * - Timeline-based log analysis with customizable time ranges
 * - Raw packet data viewing and download for forensic analysis
 * - Export functionality for compliance and reporting requirements
 * - Integration with external analysis tools through data export
 *
 * Log Types Supported:
 * - Security Alerts: High-priority security events requiring attention
 * - Packet Logs: Detailed packet inspection records with metadata
 * - System Events: Service status changes and configuration updates
 * - Audit Logs: Administrative actions and system access records
 *
 * Analysis Capabilities:
 * - Pattern recognition and anomaly detection visualization
 * - Statistical analysis with charts and trend indicators
 * - Correlation analysis between different log sources
 * - Threat intelligence integration and IOC matching
 * - Compliance reporting and audit trail generation
 *
 * @package OPNsense\AdvInspector
 * @author Pierpaolo Casati
 */
class LogsController extends \OPNsense\Base\IndexController
{
    /**
     * Render the main log management and analysis interface
     *
     * This action serves as the primary entry point for the log management system,
     * rendering a comprehensive interface that provides security analysts and system
     * administrators with powerful tools for log analysis, forensic investigation,
     * and compliance reporting.
     *
     * The interface is designed to handle large volumes of log data efficiently,
     * providing both real-time monitoring capabilities and historical analysis
     * tools. The system supports multiple log formats and provides advanced
     * filtering, searching, and visualization capabilities.
     *
     * Interface Components:
     * The rendered page includes several key components:
     * - Log type selector (alerts, packets, system events)
     * - Advanced search and filtering controls with boolean logic support
     * - Real-time log streaming with configurable refresh intervals
     * - Timeline visualization with zoom and pan capabilities
     * - Detailed log entry viewer with syntax highlighting
     * - Export controls supporting multiple formats (CSV, JSON, PCAP)
     * - Statistical dashboards with charts and metrics
     *
     * Advanced Analysis Features:
     * - Pattern matching with regular expression support
     * - IP geolocation mapping and visualization
     * - Protocol analysis with detailed packet inspection
     * - Threat intelligence correlation and IOC matching
     * - Anomaly detection with machine learning insights
     * - Custom query builder for complex log analysis
     *
     * Forensic Investigation Tools:
     * - Packet reconstruction and payload analysis
     * - Session tracking and connection analysis
     * - Evidence collection and chain of custody
     * - Timeline reconstruction for incident analysis
     * - Raw data export for external tool analysis
     * - Automated report generation for investigations
     *
     * API Integration:
     * The client-side interface communicates with multiple API endpoints:
     * - /api/advinspector/logs/read - Primary log data retrieval with filtering
     * - /api/advinspector/logs/download - Raw packet data downloads for analysis
     * - /api/advinspector/alerts/list - Security alert data with enrichment
     * - /api/advinspector/alerts/stats - Statistical analysis and trending
     * - Custom endpoints for advanced analytics and threat intelligence
     *
     * Performance and Scalability:
     * - Efficient pagination for large log datasets
     * - Client-side caching to reduce server load
     * - Progressive loading with infinite scroll capabilities
     * - Background processing for complex analytics
     * - Compressed data transfer for improved performance
     * - Optimized database queries with proper indexing
     *
     * @route GET /ui/advinspector/logs
     *
     * @return void This method renders a view template and does not return data
     *
     * View Template: 'OPNsense/AdvInspector/logs'
     * - Template Location: /usr/local/opnsense/mvc/app/views/OPNsense/AdvInspector/logs.volt
     * - Contains: Complete log analysis interface with advanced controls
     * - Includes: JavaScript frameworks for data visualization and real-time updates
     * - Utilizes: DataTables for log listing, Chart.js for visualizations
     * - Integrates: Monaco Editor for query building and syntax highlighting
     *
     * Security and Compliance:
     * - Role-based access control for sensitive log data
     * - Audit logging of all log access and analysis activities
     * - Data retention policy enforcement with automatic archival
     * - Export controls with approval workflows for sensitive data
     * - Encryption for data at rest and in transit
     * - GDPR compliance features for personal data handling
     *
     * User Experience Enhancements:
     * - Responsive design optimized for various screen sizes
     * - Keyboard shortcuts for power users and analysts
     * - Customizable dashboard layouts with drag-and-drop
     * - Saved searches and query templates for efficiency
     * - Collaborative features for team-based investigations
     * - Integration with external SIEM and analysis platforms
     *
     * @throws \Exception When view template cannot be found or rendered
     * @throws \RuntimeException When required log files or directories are inaccessible
     * @throws \SecurityException When user lacks sufficient privileges for log access
     *
     * @example
     * // Security analyst accesses log interface
     * GET /ui/advinspector/logs
     * 
     * // Controller renders comprehensive log analysis template
     * Template: OPNsense/AdvInspector/logs.volt
     * 
     * // Interface loads with default view showing recent alerts
     * AJAX: GET /api/advinspector/logs/read?type=alerts&limit=100
     * 
     * // User applies filters for specific investigation
     * Filter: source_ip=192.168.1.100, time_range=last_24h, severity=high
     * AJAX: GET /api/advinspector/logs/read?type=alerts&src_ip=192.168.1.100&since=...
     * 
     * // Analyst downloads raw packet data for forensic analysis
     * Action: Click download button for specific packet
     * Request: GET /api/advinspector/logs/download/2024-01-20T10:30:45.123Z
     * Result: Binary packet file downloaded for Wireshark analysis
     */
    public function indexAction()
    {
        // Select the comprehensive log management and analysis view template
        // This template provides a full-featured interface for log analysis,
        // forensic investigation, and security monitoring with advanced
        // filtering, visualization, and export capabilities
        $this->view->pick('OPNsense/AdvInspector/logs');
    }
}