PLUGIN_NAME= advinspector
PLUGIN_VERSION= 1.0
PLUGIN_COMMENT= Advanced Packet Inspector with Zero Trust and OT low-latency support
PLUGIN_MAINTAINER= pierpaolo.casati@student.supsi.ch
PLUGIN_TIER= 3
PLUGIN_WWW= https://git.consoli.ch/students/20250400_lavsem/moretto/
PLUGIN_DIR= service
PLUGIN_DEPENDS=	os-validation-core-1.0

.include "../../Mk/plugins.mk"
