apiVersion: v1
kind: Secret
metadata:
  name: opnsense-bridge-secrets
  namespace: opnsense-bridge
type: Opaque
data:
  OPNSENSE_API_KEY: "your-api-key"  # base64-encoded: your-api-key
  OPNSENSE_API_SECRET: "your-api-secret"  # base64-encoded: your-api-secret
  SMTP_USERNAME: "your-smtp-usarname"  # base64-encoded: bridge@company.com
  SMTP_PASSWORD: "your-smtp-password"  # base64-encoded: your-smtp-password
  SLACK_WEBHOOK_URL: ""  # base64-encoded
  TEAMS_WEBHOOK_URL: ""  # base64-encoded
  JWT_SECRET_KEY: "your-jwt-secret"  # base64-encoded: your-jwt-secret
  TEST_EMAIL_RECIPIENT: ""  # base64-encoded: test@example.com
  ADMIN_EMAILS: ""  # base64-encoded: admin1@example.com,admin2@example.com
  EMERGENCY_EMAILS: ""  # base64-encoded: soc@example.com
apiVersion: v1
kind: Secret
metadata:
  name: opnsense-bridge-certs
  namespace: opnsense-bridge
type: kubernetes.io/tls
data:
  tls.crt: ""  # base64-encoded server.crt
  tls.key: ""  # base64-encoded server.key
  ca.crt: ""  # base64-encoded ca.crt