apiVersion: v1
kind: Service
metadata:
  name: opnsense-monitoring-bridge
  namespace: opnsense-bridge
  labels:
    app: opnsense-monitoring-bridge
spec:
  selector:
    app: opnsense-monitoring-bridge
  ports:
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  type: ClusterIP