PLUGIN_NAME=		validation-core
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		OPNsense Validation Core Library - Shared validation framework
PLUGIN_MAINTAINER=	pierpaolo.casati@student.supsi.ch
PLUGIN_TIER=		1

.include "../../Mk/plugins.mk"