# libraries/os-validation-core/Makefile

PLUGIN_NAME=		os-validation-core
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		OPNsense Validation Core Library
PLUGIN_DEPENDS=		
PLUGIN_MAINTAINER=	pierpaolo.casati@student.supsi.ch
PLUGIN_NOPREFIX=	yes

.include "../../Mk/libraries.mk"