PLUGIN_NAME=		webguard
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Web Application Firewall and Behavioral Analysis Engine
PLUGIN_MAINTAINER=	pierpaolo.casati@student.supsi.ch
PLUGIN_TIER=		3
PLUGIN_WWW=		https://git.consoli.ch/students/20250400_lavsem/moretto/
PLUGIN_DIR=		security

.include "../../Mk/plugins.mk"