PLUGIN_NAME=		webguard
PLUGIN_VERSION=		1.0.0
PLUGIN_COMMENT=		Web Application Firewall and Behavioral Analysis Engine
PLUGIN_MAINTAINER=	webguard@opnsense.org
PLUGIN_TIER=		3
PLUGIN_WWW=		https://github.com/opnsense/plugins/tree/master/security/webguard/
PLUGIN_DIR=		security

.include "../../Mk/plugins.mk"