PLUGIN_NAME= netzones
PLUGIN_VERSION= 1.0
PLUGIN_COMMENT= "Network Zone Manager with Zero Trust Policies"
PLUGIN_MAINTAINER= pierpaolo.casati@student.supsi.ch
PLUGIN_TIER= 3
PLUGIN_WWW= https://git.consoli.ch/students/20250400_lavsem/moretto/
PLUGIN_DIR= service

.include "../../Mk/plugins.mk"